"""add_feasibility_table

Revision ID: 9994d71d1392
Revises: 
Create Date: 2026-02-10 11:25:20.701557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '9994d71d1392'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if table already exists (e.g., created by init_db.py)
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    
    if 'feasibilities' in tables:
        # Table already exists, skip creation
        print("Table 'feasibilities' already exists, skipping creation")
        return
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feasibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('high_level_design', sa.Text(), nullable=True),
    sa.Column('risks', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('open_questions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_feasibility', sa.String(length=100), nullable=True),
    sa.Column('rough_estimate', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('task_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibilities_chat_id'), 'feasibilities', ['chat_id'], unique=False)
    op.create_index(op.f('ix_feasibilities_id'), 'feasibilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feasibilities_id'), table_name='feasibilities')
    op.drop_index(op.f('ix_feasibilities_chat_id'), table_name='feasibilities')
    op.drop_table('feasibilities')
    # ### end Alembic commands ###
