"""add_project_features_table

Revision ID: add_project_features_001
Revises: 9994d71d1392
Create Date: 2026-02-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'add_project_features_001'
down_revision: Union[str, Sequence[str], None] = '9994d71d1392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if table already exists (e.g., created by init_db.py)
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    
    if 'project_features' in tables:
        # Table already exists, skip creation
        print("Table 'project_features' already exists, skipping creation")
        return
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('feature_name', sa.String(length=500), nullable=False),
    sa.Column('high_level_overview', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('dependencies', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('key_considerations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('discovery_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_features_chat_id'), 'project_features', ['chat_id'], unique=False)
    op.create_index(op.f('ix_project_features_id'), 'project_features', ['id'], unique=False)
    op.create_index(op.f('ix_project_features_project_id'), 'project_features', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_features_project_id'), table_name='project_features')
    op.drop_index(op.f('ix_project_features_id'), table_name='project_features')
    op.drop_index(op.f('ix_project_features_chat_id'), table_name='project_features')
    op.drop_table('project_features')
    # ### end Alembic commands ###

